// Generated by CoffeeScript 2.3.0
// # IIS extra status code

// Microsoft's Internet Information Services (IIS) web server expands the 4xx error space to signal errors with the client's request.
var k, ref, status, v;

status = require('.');

// Import default status codes.
for (k in status) {
  v = status[k];
  if (k === 'extra') {
    continue;
  }
  module.exports[k] = v;
}

ref = status.extra.iis;
// Merge default status codes with IIS status codes.
for (k in ref) {
  v = ref[k];
  module.exports[k] = v;
}
